/** Help dialog / CLI keybind reference — single source of truth. */

export type HelpTab = "general" | "commands" | "providers";
export type HelpCliSection = "keyboard" | "commands" | "providers";
export type HelpRow =
  | { kind: "binding"; key: string; desc: string; indent?: number }
  | { kind: "section"; label: string }
  | { kind: "spacer" };

export const HELP_TABS: { id: HelpTab; label: string; cliSection: HelpCliSection }[] = [
  { id: "general", label: "General", cliSection: "keyboard" },
  { id: "commands", label: "Commands", cliSection: "commands" },
  { id: "providers", label: "Providers", cliSection: "providers" },
];

export const KEYBINDS: Record<HelpTab, HelpRow[]> = {
  general: [
    { kind: "binding", key: "/", desc: "Open search mode", indent: 1 },
    { kind: "binding", key: ":", desc: "Open command mode", indent: 1 },
    { kind: "binding", key: "?", desc: "Open help dialog", indent: 1 },
    { kind: "binding", key: "esc", desc: "Back / clear current mode", indent: 1 },
    { kind: "binding", key: "f", desc: "Fetch from remote", indent: 1 },
    { kind: "binding", key: "m", desc: "Open menu dialog", indent: 1 },
    { kind: "binding", key: "q", desc: "Quit", indent: 1 },
    { kind: "binding", key: "tab", desc: "Cycle provider view (Git → providers)", indent: 1 },
    { kind: "spacer" },
    { kind: "section", label: "Graph" },
    { kind: "binding", key: "a", desc: "Enter ancestry mode", indent: 1 },
    { kind: "binding", key: "enter", desc: "Focus details / open compact detail dialog", indent: 1 },
    { kind: "binding", key: "g", desc: "First commit", indent: 1 },
    { kind: "binding", key: "G", desc: "Last commit", indent: 1 },
    { kind: "binding", key: "p", desc: "Enter path mode", indent: 1 },
    { kind: "binding", key: "shift + ←/→", desc: "Switch project", indent: 1 },
    { kind: "binding", key: "shift + ↑/↓", desc: "Jump 10 commits", indent: 1 },
    { kind: "binding", key: "↑/↓  or  j/k", desc: "Navigate commits", indent: 1 },
    { kind: "binding", key: "→  or  l", desc: "Focus detail panel", indent: 1 },
    { kind: "spacer" },
    { kind: "section", label: "Details" },
    { kind: "binding", key: "enter", desc: "Activate selected item", indent: 1 },
    { kind: "binding", key: "g", desc: "Top", indent: 1 },
    { kind: "binding", key: "G", desc: "Bottom", indent: 1 },
    { kind: "binding", key: "shift + ↑/↓", desc: "Jump 10 items", indent: 1 },
    { kind: "binding", key: "↑/↓  or  j/k", desc: "Navigate items", indent: 1 },
    { kind: "binding", key: "←  or  h", desc: "Previous tab / exit details on first tab", indent: 1 },
    { kind: "binding", key: "→  or  l", desc: "Next tab", indent: 1 },
    { kind: "spacer" },
    { kind: "section", label: "Menu" },
    { kind: "binding", key: "enter", desc: "Activate / start edit", indent: 1 },
    { kind: "binding", key: "esc", desc: "Close", indent: 1 },
    { kind: "binding", key: "↑/↓", desc: "Move selection", indent: 1 },
    { kind: "binding", key: "←/→  or  h/l", desc: "Switch tabs", indent: 1 },
    { kind: "spacer" },
    { kind: "section", label: "Theme" },
    { kind: "binding", key: "enter", desc: "Confirm theme", indent: 1 },
    { kind: "binding", key: "↑/↓", desc: "Move selection", indent: 1 },
    { kind: "spacer" },
    { kind: "section", label: "Help" },
    { kind: "binding", key: "g", desc: "Top", indent: 1 },
    { kind: "binding", key: "G", desc: "Bottom", indent: 1 },
    { kind: "binding", key: "↑/↓  or  j/k", desc: "Scroll help", indent: 1 },
    { kind: "binding", key: "←/→  or  h/l", desc: "Switch tabs", indent: 1 },
    { kind: "spacer" },
    { kind: "section", label: "Diff + Blame" },
    { kind: "binding", key: "b", desc: "Toggle blame", indent: 1 },
    { kind: "binding", key: "c", desc: "Cycle view mode", indent: 1 },
    { kind: "binding", key: "esc", desc: "Close", indent: 1 },
    { kind: "binding", key: "v", desc: "Toggle full file view", indent: 1 },
    { kind: "binding", key: "w", desc: "Toggle line wrap", indent: 1 },
    { kind: "binding", key: "↑/↓  or  j/k", desc: "Scroll lines", indent: 1 },
    { kind: "binding", key: "←/→  or  h/l", desc: "Previous / next file", indent: 1 },
    { kind: "spacer" },
    { kind: "section", label: "CI Log" },
    { kind: "binding", key: "c", desc: "Cycle view mode", indent: 1 },
    { kind: "binding", key: "esc", desc: "Close", indent: 1 },
    { kind: "binding", key: "o", desc: "Open provider run in browser", indent: 1 },
    { kind: "binding", key: "w", desc: "Toggle line wrap", indent: 1 },
    { kind: "binding", key: "↑/↓  or  j/k", desc: "Scroll lines", indent: 1 },
    { kind: "binding", key: "←/→  or  h/l", desc: "Previous / next job", indent: 1 },
    { kind: "spacer" },
    { kind: "section", label: "OpenShift Resource" },
    { kind: "binding", key: "c", desc: "Cycle view mode", indent: 1 },
    { kind: "binding", key: "esc", desc: "Close", indent: 1 },
    { kind: "binding", key: "r", desc: "Restart log follow / refresh log", indent: 1 },
    { kind: "binding", key: "w", desc: "Toggle line wrap", indent: 1 },
    { kind: "binding", key: "g/G", desc: "Top / bottom", indent: 1 },
    { kind: "binding", key: "↑/↓  or  j/k", desc: "Scroll", indent: 1 },
    { kind: "spacer" },
    { kind: "section", label: "Repository Selector" },
    { kind: "binding", key: "enter", desc: "Open selected repo", indent: 1 },
    { kind: "binding", key: "esc", desc: "Close / back", indent: 1 },
    { kind: "binding", key: "f", desc: "Forget selected repo", indent: 1 },
    { kind: "binding", key: "↑/↓  or  j/k", desc: "Move selection", indent: 1 },
  ],
  commands: [
    { kind: "binding", key: ":ancestry", desc: "Highlight first-parent ancestry" },
    { kind: "binding", key: ":branches", desc: "Open menu on Branches tab" },
    { kind: "binding", key: ":clear", desc: "Dismiss current status message" },
    { kind: "binding", key: ":debug", desc: "Toggle debug dialog" },
    { kind: "binding", key: ":fetch", desc: "Fetch from remote" },
    { kind: "binding", key: ":help", desc: "Open help dialog" },
    { kind: "binding", key: ":menu", desc: "Open menu dialog" },
    { kind: "binding", key: ":path", desc: "Switch to path mode" },
    { kind: "binding", key: ":providers", desc: "Open menu on Providers tab" },
    { kind: "binding", key: ":quit", desc: "Quit application" },
    { kind: "binding", key: ":reload", desc: "Reload repository data from disk" },
    { kind: "binding", key: ":repo", desc: "Open menu on Repository tab" },
    { kind: "binding", key: ":search", desc: "Switch to search mode" },
    { kind: "binding", key: ":switch", desc: "Open repository switcher" },
    { kind: "binding", key: ":theme", desc: "Open theme dialog" },
  ],
  providers: [
    { kind: "section", label: "GitHub" },
    {
      kind: "binding",
      key: "Enabled",
      desc: "If enabled, allows switching the provider in the graph view. This requires a valid token and allowed host",
      indent: 1,
    },
    {
      kind: "binding",
      key: "GitHub Token",
      desc: "Use personal access token as environment variable for GitHub API authentication. Default is GITHUB_TOKEN",
      indent: 1,
    },
    {
      kind: "binding",
      key: "Host",
      desc: "Shows the current host of the remote repository",
      indent: 1,
    },
    {
      kind: "binding",
      key: "Allow hosts",
      desc: "Enable for non-github.com remotes if the repository is not hosted on github.com.",
      indent: 1,
    },
    {
      kind: "binding",
      key: "Cache count",
      desc: "Maximum cached commit run snapshots per repository. Options: 10, 20, 50.",
      indent: 1,
    },
    {
      kind: "binding",
      key: "Fetch size",
      desc: "How many graph commits are queried for workflow runs. Options: 10, 20, 50.",
      indent: 1,
    },
    {
      kind: "binding",
      key: "Auto refresh",
      desc: "Re-query running workflow SHAs while the GitHub view is focused. Options: off, 2m, 5m, 10m. Default 2m. Git Auto refresh stays git-only.",
      indent: 1,
    },
    { kind: "spacer" },
    { kind: "section", label: "Jenkins" },
    {
      kind: "binding",
      key: "Enabled",
      desc: "If enabled, allows switching to the Jenkins provider in the graph view.",
      indent: 1,
    },
    {
      kind: "binding",
      key: "Username",
      desc: "Jenkins username for Basic auth.",
      indent: 1,
    },
    {
      kind: "binding",
      key: "Token",
      desc: "Environment variable holding a Jenkins API token. Default is JENKINS_TOKEN.",
      indent: 1,
    },
    {
      kind: "binding",
      key: "Cache count",
      desc: "Maximum cached commit build snapshots per repository. Options: 10, 20, 50.",
      indent: 1,
    },
    {
      kind: "binding",
      key: "Fetch size",
      desc: "How many graph commits are queried, and how many recent builds to inspect per job. Options: 10, 20, 50.",
      indent: 1,
    },
    {
      kind: "binding",
      key: "Auto refresh",
      desc: "Re-query running Jenkins builds while the Jenkins view is focused. Options: off, 2m, 5m, 10m. Default 2m. Git Auto refresh stays git-only.",
      indent: 1,
    },
    {
      kind: "binding",
      key: "New job",
      desc: "Add a job or multibranch pipeline URL. Type is detected automatically; up to 25 enabled branches load across all parents.",
      indent: 1,
    },
    { kind: "spacer" },
    { kind: "section", label: "OpenShift" },
    {
      kind: "binding",
      key: "Enabled",
      desc: "Allow switching to the OpenShift provider in the graph view.",
      indent: 1,
    },
    {
      kind: "binding",
      key: "Server",
      desc: "OpenShift API server URL.",
      indent: 1,
    },
    {
      kind: "binding",
      key: "Token",
      desc: "Environment variable holding an OpenShift API token. Default is OPENSHIFT_TOKEN.",
      indent: 1,
    },
    {
      kind: "binding",
      key: "Cache count",
      desc: "Maximum cached commit Build snapshots per repository. Options: 10, 20, 50.",
      indent: 1,
    },
    {
      kind: "binding",
      key: "Fetch size",
      desc: "How many graph commits are eligible for background Build matching. Options: 10, 20, 50.",
      indent: 1,
    },
    {
      kind: "binding",
      key: "Auto refresh",
      desc: "Poll Builds and ImageStreamTags while the OpenShift view is focused. Options: off, 2m, 5m, 10m. Default 2m. Live Deploy/DC/Pod use watch, not this timer. Git Auto refresh stays git-only.",
      indent: 1,
    },
    {
      kind: "binding",
      key: "Annotation",
      desc: "Commit SHA key. Labels first, then annotations, on Builds, Deployments, and ImageStreamTags. Default is dev/commit-sha.",
      indent: 1,
    },
    {
      kind: "binding",
      key: "New namespace",
      desc: "Add a namespace to inventory.",
      indent: 1,
    },
    { kind: "spacer" },
    { kind: "section", label: "Snyk" },
    {
      kind: "binding",
      key: "Enabled",
      desc: "Allow switching to the Snyk provider and scanning exact commits with Snyk Open Source.",
      indent: 1,
    },
    {
      kind: "binding",
      key: "Token",
      desc: "Environment variable holding a Snyk API token. Default is SNYK_TOKEN.",
      indent: 1,
    },
    {
      kind: "binding",
      key: "Cache count",
      desc: "Maximum cached commit scans per repository. Options: 10, 20, 50.",
      indent: 1,
    },
    {
      kind: "binding",
      key: "New branch",
      desc: "Add a concrete local branch. Its tip auto-scans only while the Snyk view is focused and has no cache. Other views read cache only.",
      indent: 1,
    },
    {
      kind: "binding",
      key: "Scan / Rescan commit",
      desc: "Open commit details, select Scan commit or Rescan commit, and press Enter. Existing results remain historical snapshots until rescanned.",
      indent: 1,
    },
  ],
};
