/** Help dialog / CLI keybind reference — single source of truth. */

export type HelpTab = "general" | "commands" | "providers";
export type HelpRow =
  | { kind: "binding"; key: string; desc: string; indent?: number }
  | { kind: "section"; label: string }
  | { kind: "spacer" };

export const HELP_TABS: { id: HelpTab; label: string }[] = [
  { id: "general", label: "General" },
  { id: "commands", label: "Commands" },
  { id: "providers", label: "Providers" },
];

export const KEYBINDS: Record<HelpTab, HelpRow[]> = {
  general: [
    { kind: "section", label: "App" },
    { kind: "binding", key: "/", desc: "Open search mode" },
    { kind: "binding", key: ":", desc: "Open command mode" },
    { kind: "binding", key: "?", desc: "Open help dialog" },
    { kind: "binding", key: "esc", desc: "Back / clear current mode" },
    { kind: "binding", key: "f", desc: "Fetch from remote" },
    { kind: "binding", key: "m", desc: "Open menu dialog" },
    { kind: "binding", key: "q", desc: "Quit" },
    { kind: "binding", key: "tab", desc: "Cycle provider view (git → CI)" },
    { kind: "spacer" },
    { kind: "section", label: "Graph" },
    { kind: "binding", key: "a", desc: "Enter ancestry mode", indent: 1 },
    { kind: "binding", key: "enter", desc: "Open detail dialog in compact layout", indent: 1 },
    { kind: "binding", key: "g", desc: "First commit", indent: 1 },
    { kind: "binding", key: "G", desc: "Last commit", indent: 1 },
    { kind: "binding", key: "p", desc: "Enter path mode", indent: 1 },
    { kind: "binding", key: "shift ←/→", desc: "Cycle modes", indent: 1 },
    { kind: "binding", key: "shift ↑/↓", desc: "Jump 10 commits", indent: 1 },
    { kind: "binding", key: "↑/↓  or  j/k", desc: "Navigate commits", indent: 1 },
    { kind: "binding", key: "→  or  l", desc: "Focus detail panel", indent: 1 },
    { kind: "spacer" },
    { kind: "section", label: "Details" },
    { kind: "binding", key: "enter", desc: "Activate selected item", indent: 1 },
    { kind: "binding", key: "g", desc: "Top", indent: 1 },
    { kind: "binding", key: "G", desc: "Bottom", indent: 1 },
    { kind: "binding", key: "shift ↑/↓", desc: "Jump 10 items", indent: 1 },
    { kind: "binding", key: "↑/↓  or  j/k", desc: "Navigate items", indent: 1 },
    { kind: "binding", key: "←  or  h", desc: "Previous tab / exit details on first tab", indent: 1 },
    { kind: "binding", key: "→  or  l", desc: "Next tab", indent: 1 },
    { kind: "spacer" },
    { kind: "section", label: "Menu" },
    { kind: "binding", key: "enter", desc: "Activate / start edit", indent: 1 },
    { kind: "binding", key: "esc", desc: "Close", indent: 1 },
    { kind: "binding", key: "↑/↓", desc: "Move selection", indent: 1 },
    { kind: "binding", key: "←/→  or  h/l", desc: "Switch tabs", indent: 1 },
    { kind: "spacer" },
    { kind: "section", label: "Theme" },
    { kind: "binding", key: "enter", desc: "Confirm theme", indent: 1 },
    { kind: "binding", key: "↑/↓", desc: "Move selection", indent: 1 },
    { kind: "spacer" },
    { kind: "section", label: "Help" },
    { kind: "binding", key: "g", desc: "Top", indent: 1 },
    { kind: "binding", key: "G", desc: "Bottom", indent: 1 },
    { kind: "binding", key: "↑/↓  or  j/k", desc: "Scroll help", indent: 1 },
    { kind: "binding", key: "←/→  or  h/l", desc: "Switch tabs", indent: 1 },
    { kind: "spacer" },
    { kind: "section", label: "Diff + Blame" },
    { kind: "binding", key: "b", desc: "Toggle blame", indent: 1 },
    { kind: "binding", key: "c", desc: "Cycle view mode", indent: 1 },
    { kind: "binding", key: "esc", desc: "Close", indent: 1 },
    { kind: "binding", key: "v", desc: "Toggle full file view", indent: 1 },
    { kind: "binding", key: "w", desc: "Toggle line wrap", indent: 1 },
    { kind: "binding", key: "↑/↓  or  j/k", desc: "Scroll lines", indent: 1 },
    { kind: "binding", key: "←/→  or  h/l", desc: "Previous / next file", indent: 1 },
    { kind: "spacer" },
    { kind: "section", label: "Job Log" },
    { kind: "binding", key: "c", desc: "Cycle view mode", indent: 1 },
    { kind: "binding", key: "esc", desc: "Close", indent: 1 },
    { kind: "binding", key: "w", desc: "Toggle line wrap", indent: 1 },
    { kind: "binding", key: "↑/↓  or  j/k", desc: "Scroll lines", indent: 1 },
    { kind: "binding", key: "←/→  or  h/l", desc: "Previous / next job", indent: 1 },
    { kind: "spacer" },
    { kind: "section", label: "Repository Selector" },
    { kind: "binding", key: "enter", desc: "Open selected repo", indent: 1 },
    { kind: "binding", key: "esc", desc: "Close / back", indent: 1 },
    { kind: "binding", key: "f", desc: "Forget selected repo", indent: 1 },
    { kind: "binding", key: "↑/↓  or  j/k", desc: "Move selection", indent: 1 },
  ],
  commands: [
    { kind: "binding", key: ":ancestry", desc: "Highlight first-parent ancestry" },
    { kind: "binding", key: ":branches", desc: "Open menu on Branches tab" },
    { kind: "binding", key: ":clear", desc: "Dismiss current status message" },
    { kind: "binding", key: ":fetch", desc: "Fetch from remote" },
    { kind: "binding", key: ":help", desc: "Open help dialog" },
    { kind: "binding", key: ":menu", desc: "Open menu dialog" },
    { kind: "binding", key: ":path", desc: "Switch to path mode" },
    { kind: "binding", key: ":providers", desc: "Open menu on Providers tab" },
    { kind: "binding", key: ":quit", desc: "Quit application" },
    { kind: "binding", key: ":reload", desc: "Reload repository data from disk" },
    { kind: "binding", key: ":repo", desc: "Open menu on Repository tab" },
    { kind: "binding", key: ":search", desc: "Switch to search mode" },
    { kind: "binding", key: ":switch", desc: "Open repository switcher" },
    { kind: "binding", key: ":theme", desc: "Open theme dialog" },
  ],
  providers: [
    { kind: "section", label: "GitHub" },
    {
      kind: "binding",
      key: "Enabled",
      desc: "If enabled, allows switching the provider in the graph view. This requires a valid token and allowed host",
    },
    {
      kind: "binding",
      key: "GitHub Token",
      desc: "Use personal access token as environment variable for GitHub API authentication. Default is GITHUB_TOKEN",
    },
    {
      kind: "binding",
      key: "Host",
      desc: "Shows the current host of the remote repository",
    },
    {
      kind: "binding",
      key: "Allow hosts",
      desc: "Enable for non-github.com remotes if the repository is not hosted on github.com. This allows using GitHub provider features with GitHub Enterprise or GitHub Cloud instances accessed via custom domains.",
    },
  ],
};
